name: openlibrary
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Value equality
  equatable: ^2.0.3
  #dartz
  dartz: ^0.10.0
  #dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.0
  # Remote API
  connectivity: ^3.0.6
  internet_connection_checker: ^0.0.1+1

  #Route
  auto_route: ^2.3.2
  #mobx
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.2  
  build_runner: ^2.1.1
  auto_route_generator: ^2.3.2
  mobx_codegen: ^2.0.4


flutter:
  uses-material-design: true
